### DISCUSSION TITLE
Group specific join message

### DISCUSSION THREAD

**Discussion by TKDKid1000** [EssentialsX/Essentials#3993] [Ideas and Feature Suggestions]
Here is my idea, the ability to have certain messages for when certain groups join the server. Like if you want the VIP group to say “name joined the game” but not the Default group to say that, in the config it could look something like this:
```yaml
custom-join-message: “for everyone”
join-messages:
  vip: “only vip gets this”
```
And maybe the same for quit messages.
