### DISCUSSION TITLE
Add confirmation to delete a home

### DISCUSSION THREAD

**Discussion by thiagogebrimm** [EssentialsX/Essentials#4381] [Ideas and Feature Suggestions] [answered]
It would be nice for silly people like me

**Comment by Chew** [comment, marked as answer]
These already exist:

```yml
# A list of commands that should have their complementary confirm commands enabled by default.
# This is empty by default, for the latest list of valid commands see the latest source config.yml.
default-enabled-confirm-commands:

# Should players be asked to provide confirmation for homes which they attempt to overwrite?
confirm-home-overwrite: false
```
