### DISCUSSION TITLE
essentials discord: ip-adress filter

### DISCUSSION THREAD

**Discussion by TheLethalGoose** [EssentialsX/Essentials#4527] [Ideas and Feature Suggestions] [answered]
If you decide to mirror the console to discord. the option to filter out ips from the console logs would be a good idea.
Otherwise you are sharing them with a company that can do whatever they like with their collected data.

**Comment by JRoy** [comment, marked as answer]
Will be added in https://github.com/EssentialsX/Essentials/pull/4534

You'd want to add the following to your config to filter ip addresses when merged;
```yml
# Console relay settings
# The console relay sends every message shown in the console to a Discord channel.
console:
  ...
  # A regex pattern which will not sending matching console messages to Discord.
  console-filter: "(?:[0-9]{1,3}\.){3}[0-9]{1,3}"
```
