### DISCUSSION TITLE
Option to disable custom join message on first join!

### DISCUSSION THREAD

**Discussion by NickReagan** [EssentialsX/Essentials#4557] [Ideas and Feature Suggestions]
I would like to request an option under the essentials spawn module like this;
"
#Do you want the custom join message to send on a players first join? If not set to "false".
customjoinmessageonfirstjoin: true
"
This way people can select whether they want just the first join message or both.

**Comment by Chew** [comment]
This?

```yml
newbies:
  # Should we announce to the server when someone logs in for the first time?
  # If so, use this format, replacing {DISPLAYNAME} with the player name.
  # If not, set to ''
  #announce-format: ''
  announce-format: '&dWelcome {DISPLAYNAME}&d to the server!'
```
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L1119-L1124

In which case, simply set to ''
