### DISCUSSION TITLE
/discord command

### DISCUSSION THREAD

**Discussion by DaliborTrampota** [EssentialsX/Essentials#4598] [Ideas and Feature Suggestions] [answered]
please give us an option to have /discord command so players can get clickable link to our discord servers. Something like this:

tellraw @p {"text":"Discord Invite","color":"aqua","clickEvent":{"action":"open_url","value":"inv link here"},"hoverEvent":{"action":"show_text","contents":["Join our discord"]}}

**Comment by Andre601** [comment]
I think you *can* make a command alias in Spigot's `commands.yml` like this:
```yaml
aliases:
  discord:
  - 'minecraft:tellraw @p {"text":"Discord Invite","color":"aqua","clickEvent":{"action":"open_url","value":"inv link here"},"hoverEvent":{"action":"show_text","contents":["Join our discord"]}}'
```

Not sure if command aliases actually support the `@p` selector in the commands, but I think that since it (most likely) executes the command as player and that you can use `@p` in Minecraft commands should this work.
