### DISCUSSION TITLE
Suggestions for EssentialsXDiscord module

### DISCUSSION THREAD

**Discussion by Andre601** [EssentialsX/Essentials#4605] [Ideas and Feature Suggestions]
Here are some suggestions for the EssentialsXDiscord module with the hope to enhance the plugin further.

### `{timestamp:<format>}` placeholder
Using the `{timestamp}` placeholder for the console relay is a bit sub-optimal, if you want to use inline-code for the formatting.

In my case would a formatting like
```
`[{timestamp} {level}]` {message}
```
end up as
`[<t:1635781050:T> INFO] Checking version, please wait...`

because of EssentialsXDiscord using the timestamp format from Discord.

My suggestion is to add an optional pattern you can set, which at the end would return a raw string of the timestamp, rather than the `<t:<time>:T>` pattern.
The format would simply be a SimpleDateFormat from Java.

----
### Custom commands
I feel like it could be somewhat useful to give server owners and admins the option to define own commands to execute in Discord.
While the `/execute` command exists could it sometimes be a bit easier for people, especially staff, to have a pre-made command with all the required options set.

I can imagine the following setup in the config to achieve this:
```yaml
custom-commands:
  - name: 'ban' # Main name used for /<name>
    hide-command: true
    allowed-roles:
      - 'Admin'
    options:
      # Entries would be in the format <Name>:<OptionType>[:Optional]
      - 'name:String'
      - 'reason:String:true'
    # Command pattern to execute on the console.
    # {placeholders} could be own, PAPI or those defined under "options"
    minecraft-command: 'ban {name} {reason}'
```
This entire things is obviously complicated and it's up to debate if people would actually use it, but I wanted to drop it here to hopefully start a discussion about if commands could be improved.

Again, I'm aware that the execute command exists, but people may not remember the patterns or misstype something and having often used commands integrated as an actual Discord command could ease up things.
