### DISCUSSION TITLE
Multiple guilds support for discord broadcast command

### DISCUSSION THREAD

**Discussion by Rubenicos** [EssentialsX/Essentials#4647] [Ideas and Feature Suggestions] [answered]
### Feature request
Option to define more than one guild in config to send broadcasts to them.
```yaml
# The ID of your server.
guild:
  primary: 000000000000000000
  otherserver: 000000000000000000
```
**For example:**
`/discordbroadcast <channel> <msg>` Sends the message to primary guild.
`/discordbroadcast [guild]:<channel> <msg>` Sends the message to defined guild
