### DISCUSSION TITLE
autoplug compatibility

### DISCUSSION THREAD

**Discussion by cTurtle98** [EssentialsX/Essentials#4719] [Ideas and Feature Suggestions] [answered]
it would be nice if autoplug could update the essentialsx plugins automatically https://autoplug.one/faq

**Comment by mdcfe** [comment, marked as answer]
No. Automatically updating server software and plugins is a recipe for disaster, and we do not intend to support any solutions to that end.

**Comment by Osiris-Team** [comment]
Also it would require them to actually link to the plugin jar instead of the downloads page.
At the moment u can use our alternative updating method via jenkins.
Just insert this in your plugins config:
```yaml
  Essentials: 
    exclude: false
    version: 1344
    latest-version: 1344
    author: Zenexer
    spigot-id: 871
    bukkit-id: 0
    custom-author: 
    custom-check-url: 
    custom-download-url: 
    ignore-content-type: false
    alternatives: 
      github: 
        repo-name: 
        asset-name: 
      jenkins: 
        project-url: https://ci.ender.zone/job/EssentialsX/
        artifact-name: EssentialsX
        build-id: 1344
```
