### DISCUSSION TITLE
Support discord relay for multiple simultaneous channels/guilds

### DISCUSSION THREAD

**Discussion by cupanoodle** [EssentialsX/Essentials#4749] [Ideas and Feature Suggestions]
The config could looks something like this and allow sending messages to separate discord guild/channels.
```yml
message-types:
  join: primary
  leave: secondary
  chat: [ primary, secondary ]
```

currently the settings are just read in a a single string: https://github.com/EssentialsX/Essentials/blob/680d3230ea382b0cf9f146008a878c9aa9218f11/EssentialsDiscord/src/main/java/net/essentialsx/discord/DiscordSettings.java#L86
