### DISCUSSION TITLE
Custom AFK list name

### DISCUSSION THREAD

**Discussion by ViewShumoon** [EssentialsX/Essentials#4777] [Ideas and Feature Suggestions]
Allow player or authorized player to custom their AFK list name.

### Usage

/afk custom "I'll Back in 3 min"

then 
``` Java
sendMessage( AFK_DEFAULT_MESSAGE + "and left a message: " + custom );
```
then the Player List showing:
```
 - I'll Back in 3 min - Player name
 - Other online player name
 ...
```
More like: 
```
 - Have dinner - <Player - name>
 - Take a break - <Player - name>
 - Showering - <Player - name>
 - On Nuclear Reaction - <Player - name>
 - I'll be back in 5 min, BTW, tell Steve to harvest the carrot - <Player - name>
 ...
 ```
### Permissions

essentials.afk.customName

### Config
``` YAML
# Whether should limited the AFK name to a list or just let player to custom it
# or use its opposite:  limited-afk-name: true
allow-custom-afk-name: false

# Showing on "onTabComplete"
afk-available-name-list:
  - "AFK"
  - "Have dinner"
  - "Showering"
  - "Some fancy colorful name"
  - ...
 
# the Max character size of custom afk name
maximum-akf-custom-name-size: 16 

# Whoes ignore the "essentials.afk.customName" permissions
allways-allow-custom-afk-name:
  - op
  - staff
  - patron
  - ...

# To be continue...
```
Thanks to the developers for all your hard work.
