### DISCUSSION TITLE
Permission exemption for AntiBuild piston & dispenser blacklist

### DISCUSSION THREAD

**Discussion by mibby** [EssentialsX/Essentials#4855] [Ideas and Feature Suggestions]
Currently EssentialsX Antibuild only has exemption for break, placement, & usage.

i.e.
https://github.com/EssentialsX/Essentials/blob/63cbf7e2da45dceeb8314d89bde08f6b7f8b4f34/EssentialsAntiBuild/src/main/java/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java#L286

However AntiBuild protection blacklist also supports piston & dispenser.
```
  blacklist:

    # Which blocks should people be prevented from placing?
    placement:

    # Which items should people be prevented from using?
    usage: LAVA_BUCKET

    # Which blocks should people be prevented from breaking?
    break:

    # Which blocks should not be pushed by pistons?
    piston:

    # Which blocks should not be dispensed by dispensers
    dispenser:
```

Would it be possible to add exemption permissions for these two categories?
