### DISCUSSION TITLE
Unlocking kits based on mining level or other criteria...

### DISCUSSION THREAD

**Discussion by cboxgo69** [EssentialsX/Essentials#5217] [Q&A]
I've seen servers notify you that you have a new kit after level 10, 50, 100, 500, etc... is there something like that for EssentialsX?  

I already setup a newbies kit like this:

```
newbies:
  kit: starter
kits:
  starter:
    delay: -1
    items:
      - leatherhelmet 1
      - leathertunic 1
      - leatherpants 1
      - leatherboots 1
      - stonesword 1
      - stoneshovel 1
      - stoneaxe 1
      - stonehoe 1      
      - stonepickaxe 1      
      - goldshovel 1 name:Claim_Shovel
      - /broadcast {USERNAME} good luck mining!
```

and just wondered if there was a similar level that i could add for mining level numbers.  Thanks.
