### DISCUSSION TITLE
Discord Link - Role after Linking

### DISCUSSION THREAD

**Discussion by szymon-off** [EssentialsX/Essentials#5452] [Q&A]
https://essentialsx.net/dump.html?id=edf8a95e80ef4782875d413cc11e4223

I want to give people who link their Minecraft/discord account (using EssentialsXDiscordLink) to receive a discord role.

I tried making it so that the default Minecraft role results in receiving a discord role.

This is what I did so far, but it doesn't work for some reason(Its EssentialsDiscordLink/config.yml - Lines 26-51)

```
# MC group to Discord role sync settings
# Allows for the ability to give players Discord roles based on their Minecraft groups and/or give players Minecraft
# groups based on their Discord roles.
role-sync:
  # Whether EssentialsX DiscordLink should remove synced Discord roles from players who unlink their Minecraft account,
  # leave the Discord server, or who no longer have the groups that awarded them the role in the first place.
  remove-roles: true
  # Whether EssentialsX DiscordLink should remove synced Minecraft groups from players who unlink their Discord account,
  # or who no longer have the Discord roles that awarded them the group in the first place.
  remove-groups: true
  # The amount of time (in minutes) between which EssentialsX DiscordLink should audit player groups/roles.
  # Requires a restart after changing.
  resync-delay: 1
  # Whether EssentialsX DiscordLink should only consider the primary group of Minecraft users
  primary-group-only: false
  # Minecraft group to Discord role ID synchronization.
  # Players in the following groups listed here will receive the corresponding role ID on discord when they link
  # their Minecraft account to their Discord account.
  groups:
    default: 1082747161491537972
    admin: 11111111111111111
  # Discord role ID to Minecraft group synchronization.
  # Users with the following roles listed here will receive the corresponding group in Minecraft when they link
  # their Discord account to their Minecraft account.
  roles:
    1082747161491537972: default
```
--
1082747161491537972 id the ID of the role I want linked users to receive
☹️
