### DISCUSSION TITLE
World Alias Chat Formatting Not Working

### DISCUSSION THREAD

**Discussion by UberWienerWumbo** [EssentialsX/Essentials#5862] [Q&A] [answered]
When formatting to give my different worlds alias prefixes, so players can chat and it will display their World alias, prefix, username and then chat message. this works perfectly fine until I try to edit the world prefix, it just continues to display the full world name, even with the values changed. Short world name doesn't work either.

I'm at a stopping point until I can figure out what the issue is.

![IssueA](https://github.com/EssentialsX/Essentials/assets/43225209/adc1f4ca-8c8d-48e0-989b-81270c7f8217)
![IssueB](https://github.com/EssentialsX/Essentials/assets/43225209/7dd8b9da-7ad4-4bcc-9c40-ca90af8e87b3)
![IssueC](https://github.com/EssentialsX/Essentials/assets/43225209/5dd3b716-51c1-4551-b74e-e9abfa9f881f)

**Comment by Evidentsinger14** [comment, marked as answer]
You removed the indentation of those. 
```yaml
world-aliases:
  world: ''
  […]
```

**Reply by UberWienerWumbo** [reply]
I have this exact indentation posted in the screenshots of the thread. [ ] does not change the prefix except adding brackets to the world name. The world prefixes are formatted to show as: 
![Alias](https://github.com/EssentialsX/Essentials/assets/43225209/6c713929-c89e-4309-aead-2715c23d0da6)

**Reply by Chew** [reply]
Your screenshot does not have the provided indention.

You have this:

```yaml
world-aliases:
world: "stuff"
world_nether: "stuff"
```

You need this:

```yaml
world-aliases:
  world: "stuff"
  world_nether: "stuff"
```
