### DISCUSSION TITLE
EssentialsX 2.21.1 - The Spring to Life Update

### DISCUSSION THREAD

**Discussion by mdcfe** [EssentialsX/Essentials#6152] [Announcements]
🎉 **EssentialsX 2.21.1 is here**, bringing with it 1.21.5 support and several bug fixes.

Thanks to everyone who has contributed code to this release (many of whom are listed at the bottom of this release), as well as to everyone who has contributed to translations on [Crowdin](https://translate.essentialsx.net)!

In addition, a massive thanks to our community members who have assisted countless people with using EssentialsX across GitHub and MOSS, including @Evidentsinger14, @JasonHorkles, @ImDarkLaw, @Chew and many others.

The EssentialsX project is powered by the community. If you want to help us out, you can contribute by;
* Updating or reviewing translations on [Crowdin](https://translate.essentialsx.net)
* Help users in our support channel on [Discord](https://discord.gg/casfFyh)
* Fixing bugs or offering new features on [GitHub](https://github.com/EssentialsX/Essentials/blob/2.x/CONTRIBUTING.md)

Finally, a shoutout to our supporters on [Patreon](https://www.patreon.com/essentialsx) and [GitHub Sponsors](https://github.com/sponsors/EssentialsX/)!  
A special thanks goes to our Hero tier supporters:

- AKP
- @aternosorg
- @pebblehost
- and one anonymous supporter!

Your support helps us to continue spending hours of our free time working on and improving EssentialsX for everyone. If you've got any spare change, you can click one of the buttons below to support the EssentialsX project with a one-off or monthly pledge:

[![Patreon](https://user-images.githubusercontent.com/1917406/125179860-aca4a400-e1ea-11eb-858b-816849f542bf.png)](https://www.patreon.com/essentialsx) [![GitHub Sponsors](https://user-images.githubusercontent.com/1917406/125179862-b0d0c180-e1ea-11eb-801c-cbd52dfa9465.png)](https://github.com/sponsors/EssentialsX/)

## Supported server versions

EssentialsX officially supports the [Paper](https://papermc.io) server software. Specifically, EssentialsX is designed to work on the following Minecraft versions:

* ✅ `1.21.5` - EssentialsX actively develops for and supports this version.
* ⚠️ `1.8.8`, `1.9.4`, `1.10.2`, `1.11.2`, `1.12.2`, `1.13.2`, `1.14.4`, `1.15.2`, `1.16.5`, `1.17.1`, `1.18.2`, `1.19.4`, and `1.20.6` - these versions are still supported, but are not a priority for us, and may be dropped in a future release.
* ⚠️ Spigot is still supported but is a low priority for us, and may be dropped in a future release.

**We recommend using the latest version of Paper**. EssentialsX includes significant improvements that require Paper, including:
* Paper's async chunk loading reduces lag spikes during player teleports.
  CraftBukkit and Spigot do not support async chunk loading from plugins.
* `/anvil`, `/grindstone`, `/cartographytable`, `/loom`, `/smithingtable`, and `/stonecutter` are only supported on Paper.  
  CraftBukkit and Spigot do not support the API needed for these.
* `/recipe` on 1.12+ requires Paper to avoid a dupe bug introduced by CraftBukkit and Spigot.
* Paper contains countless overall performance optimisations over CraftBukkit and Spigot.

EssentialsX does **not** support the following Minecraft versions or server software:

* ℹ️ **Folia is not supported yet.** We are working on proper Folia support.
  **Do not attempt to use current versions of EssentialsX on Folia or forks of it - you may lose userdata.**
* 🛑 "Ultra-performance" Paper forks including Akarin, Yatopia, and similar projects.  
  These often perform non-standard behaviour and can break your worlds and installed plugins.
* 🛑 Mohist - **[The Mohist project is known to be sketchy, and has, in the past, tricked users into deleting official EssentialsX jars and installing an unofficial build.](https://essentialsx.net/do-not-use-mohist.html)**  
  We cannot guarantee the safety or functionality of unofficial builds of EssentialsX; you should avoid using Mohist where possible.
* 🛑 Other Forge/Bukkit hybrid servers including Cauldron, Thermos, Magma, CatServer, Arclight - EssentialsX is built for the Bukkit API, which does not properly support mods.  
  For modded servers running Minecraft Forge, NeoForge or Fabric, you should use [FTB Essentials](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials).
* 🛑 `1.7.10` or below.

## Upgrading to 2.21.1

If you're upgrading from **2.21.0**, you can keep your current EssentialsX config file. There are no new changes to configuration files in this release.

Upgrading from 2.20.0 or older versions of EssentialsX? See the [previous update changelogs](https://github.com/EssentialsX/Essentials/releases).

### Anchor charges deplete on Spigot even when EssentialsX Spawn overrides the spawn location

On CraftBukkit and Spigot, anchor charges will deplete regardless of the `respawn-at-anchor` due to an [unfixed bug in CraftBukkit](https://hub.spigotmc.org/jira/browse/SPIGOT-5989). This bug has been patched in Paper.

### Fly mode is reset when teleporting between worlds on Spigot

On Spigot 1.17.1 and greater, player's fly mode will be reset regardless of the `world-change-fly-reset` setting due to behavior change in vanilla. A fix for this is in place for Paper servers. (#6012)

### EssentialsX now supports 1.21.5 (#6109)

EssentialsX now officially supports Paper and Spigot 1.21.5.

### New `allowed-nicks-regex` setting (#5200)

You can now change the regex pattern which determines which nicknames are allowed. The `essentials.nick.allowunsafe` permission
can still be used to bypass this check.

```yml
# The regex pattern used to determine if a requested nickname should be allowed for use.
# If the a request nickname does not matched this pattern, the nickname will be rejected.
# Users with essentials.nick.allowunsafe will be able to bypass this check.
allowed-nicks-regex: '^[a-zA-Z_0-9§]+$'
 ```

### Discord: Support for SocialSpy with new `private-chat` message type (#5620)

You can now relay SocialSpy messages to Discord using the new `private-chat` message type.  
This is sent whenever a user sends a private message on the Minecraft server, unless they also have the `essentials.chat.spy.exempt` permission.

```yml
# Configure which Discord channels different messages will be sent to.
# You can either use the names of the channels listed above or just the id of a channel.
# If an invalid channel is used, the primary channel will be used instead.
#
# To disable a message from showing, use 'none' as the channel name.
message-types:
  ...
  # Message sent when a private message (/msg, /whisper, etc.) is sent on the Minecraft Server.
  private-chat: none
```

```yml
# The following entries allow you to customize the formatting of messages sent by the plugin.
# Each message has a description of how it is used along with placeholders that can be used.
messages:
  ...
  # This is the message that is used to relay minecraft private messages in Discord.
  # The following placeholders can be used here:
  # - {sender-username}: The username of the player sending the message
  # - {sender-displayname}: The display name of the player sending the message (This would be their nickname)
  # - {receiver-username}: The username of the player receiving the message
  # - {receiver-displayname}: The display name of the player receiving the message (This would be their nickname)
  # - {message}: The content of the message being sent
  pms-to-discord: "[SocialSpy] {sender-username} -> {receiver-username}: {message}"
```

### Other additions

* Translations have been updated with the latest community contributions on Crowdin. (#6089, #6131)
* EssentialsX's config files have been tidied up, with better wording in comments for clarity. (#6108)

### Bugs fixed from 2.21.0 and older versions

* Various issues from the Adventure text refactor have resolved. (#6114)
* Further issues with trade signs have been resolved. (#6116)
* The `/baltop` command works again on versions 1.15.2 and below. (#6115)
* Various typos in the English translation files have been fixed. (#6135, #6140)
* `/delhome` no longer sends an extra message when deleting a home that doesn't exist. (#6150)
* **Discord Link:** Unlinking your account from Discord while offline no longer causes an error. (#6111)

### Regressions fixed from 2.21.1 dev builds

The following bugs from 2.21.1 development builds have been fixed:

* The `/spawnmob` command works again on versions 1.21.5 and below. (#6121)
* You can sleep in a bed once again, regardless of whether you have `essentials.sethome.bed` or not. (#6151)

### New events

EssentialsX 2.21.1 introduces a new event:

* `SignTransactionEvent` is fired when a player is about to use a buy or sell sign. (#6071)

### New methods

* There is now a method to retrieve the most recent activity time of a User: `IUser#getLastActivityTime`. (#6101)

### Other changes

* `GlobalChatEvent` is now fired for every chat message that EssentialsX Chat processes regardless of whether a chat radius has been set. (#6113)
* `TranslatableException#getMessage` now returns plaintext once again, not unparsed MiniMessage tags. (#6134)

---

For a full commit log, [click here](https://github.com/EssentialsX/Essentials/compare/2.21.0...2.21.1).

<hr /><em>This discussion was created from the release <a href='https://github.com/EssentialsX/Essentials/releases/tag/'>EssentialsX 2.21.1 - The Spring to Life Update</a>.</em>
