### ISSUE TITLE
suggestion to add /rawbc and /rawmsg

### ISSUE THREAD

**Issue by Twi5TeD** [EssentialsX/Essentials#1116]
this would allow the message to be sent without a prefix or any format thanks

**Comment by mdcfe** [comment]
You can `/sudo <player> ping <message>` to send an unformatted message to one person, or `/execute @a ~ ~ ~ ping <message>` to send it to all players.

**Comment by Twi5TeD** [comment]
rather have it in essentials as it would be alot easier doing rawbc or rawmsg

**Comment by ghost** [comment]
Adding something like this:
```yaml
aliases:
    rawmsg:
    - "sudo $$1 ping $$2-"
    rawbc:
    - "execute @a ~ ~ ~ ping $$1-"
```

To your [Commands.yml](http://bukkit.gamepedia.com/Commands.yml) file should fix that. The syntax might not be 100% correct, but you can read through the linked wiki page to read more about it.
