### ISSUE TITLE
Command cooldown ignores /fix

### ISSUE THREAD

**Issue by AnttiMK** [EssentialsX/Essentials#1174]
Title pretty much says it all: when a cooldown is assigned to the /fix command, the actual cooldown doesn't work at all. Instead, I can use the command as much as I want.

```yaml
command-cooldowns:
  fix: 60
command-cooldown-persistence: true
```

- Essentials 2.0.1-b468
- CraftBukkit version git-Spigot-283de8b-2ad21b8 (MC: 1.11.2)

ess debug log: http://pastebin.com/9HxahC6f
