### ISSUE TITLE
Allow {username} in kit names {player} breaks anything after it

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1187]
I want to be able to name a kit item after a user but if your user has a prefix then it will break/stop any other text being displayed after it, this is for name and lore of items.
For example.
```
gunner_rankup:
    delay: -1
    items:
      - 261 1 ARROW_FIRE:2 Name:&4Gunner_Bow lore:{PLAYER}|Gunner_Bow
```
Where it says {PLAYER} gunner bow, if the user has a prefix, which most do, then the "Gunner Bow" will not be displayed at all.
