### ISSUE TITLE
Certain values generated by the /createkit command are seen as invalid

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#1283]
[comment_1]: https://github.com/EssentialsX/Essentials/issues/1283#issuecomment-471174577
[comment_2]: https://github.com/EssentialsX/Essentials/issues/1283#issuecomment-541113193
[recipe]: https://user-images.githubusercontent.com/11576465/71815026-70850600-307e-11ea-82bb-d12d329eff1d.png
[gist]: https://gist.github.com/anonymous/a8eec587ba664aefc46643884e2b9bca

When creating a new kit with the `/createkit` command are certain values set, which EssentialsX sees as "invalid".
In my example does EssentialsX set the color(s) of firework as `Color:[rgb:0x<hex code>]` which the plugin doesn't support in commands like `/kit`

## **Infos**
**Used Spigot version**: git-spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Also didn't work on 1.13 [[Link][comment_1]])

**Used EssentialsX**: 2.0.1-b481 (Also didn't work with Build 784 [[Link][comment_2]])

## **How to reproduce:**

1. Craft a firework with multiple colors. The recipe I used can be found [here][recipe].
2. Hold the firework in your inventory and type `/createkit [name] [delay]`
   - I set the kit with the name "Special" (Second test as "Example") with delay 0.
3. Copy the given text into the config. (On second test did EssentialsX add it directly)
I used [this text here][gist] and added it to the config like so:
```YAML
kits:
  # ...
  # The other kits (tools, dtools, ...)
  firework:
    delay: 6000
    items:
      - 401 1 name:Angry_Creeper color:red fade:green type:creeper power:1
      - 401 1 name:Starry_Night color:yellow,orange fade:blue type:star effect:trail,twinkle power:1
      - 401 2 name:Solar_Wind color:yellow,orange fade:red shape:large effect:twinkle color:yellow,orange fade:red shape:ball effect:trail color:red,purple fade:pink shape:star effect:trail power:1
  special: # The new added kit
    delay: 0
    items: # "power: 3" was on the next line. I placed it on the same line.
    - 'FIREWORK 3 color:Color:[rgb0xB3312C],Color:[rgb0xEB8844] shape: STAR fade:Color:[rgb0xDECF2A],Color:[rgb0x41CD34] power:3'
    - POTION 1
```
4. Reload the plugin.
1. Use the /kit command.
1. Now you get the message: "That kit is improperly defined. Contact an administrator." and the console will give the following Error:
`[Essentials] the option color:[rgb0x<hex code>],Color:[rgb0x<hex code>] is not a valid value for color.`
