### ISSUE TITLE
Kit Item Tag

### ISSUE THREAD

**Issue by d3ath2005** [EssentialsX/Essentials#1291]
#1290 
Where do I add {Unbreakable: 1}?
```
kits:
  Starter:
    delay: 86400
    items:
    - DIAMOND_PICKAXE 1 name:&eStarter_Pickaxe dig_speed:15
    - IRON_HELMET 1 name:&eStarter_Helmet
    - IRON_CHESTPLATE 1 name:&eStarter_Chestplate
    - IRON_LEGGINGS 1 name:&eStarter_Leggings
    - IRON_BOOTS 1 name:&eStarter_Boots
```
