### ISSUE TITLE
potions not working

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#1428]
```
  potiontest:
    delay: 1
    items:
    - SPLASH_POTION:16421 1
```

this gives me a missing texture item

same as /give and /i

EssentialsX version (`/essentials`): 
2.0.1 b510 as of https://github.com/drtshock/Essentials/commit/210494d0d15bd23a6c8bef13053aa16e275308ed
Server software (`/version`): 
Paper version git-Paper-1167 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
EssentialsX config (if applicable):
