### ISSUE TITLE
[BUG] Colored Signs only works for Ops

### ISSUE THREAD

**Issue by Formula350** [EssentialsX/Essentials#1590]
EssentialsX version (`/essentials`): 
*(This does not display a version, so also is technically bugged 😛 )*
````
/<command> <reload/debug>
Essentials relayed the following commands to another plugin:
v => SuperVanish:sv
````
That being said... I'm running EssX **v2.0.1 build 530**

Server software (`/version`): 
This server is running CraftBukkit version git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

EssentialsX config (if applicable): 
https://gist.github.com/Formula350/da62d759f7fc4ce10ebe2f77c2c16039

Recently updated from Spigot 1.8 to 1.11.2. I had been using md5's Essentials with original old-school GroupManager, everything worked great still even in 1.11.2, but decided it was time to move to something more current (plus I loved that you guys added the UUID into the /whois command). Nevertheless, I've had loads of issues using EssX, and since I know you don't support GroupManager, I've not bothered reporting the issues... _(such as it not recognizing `build: true` in groups, anti-build/protection snafus, to name a few)_. Currently I'm using GroupManagerX v2.2, though as I understand it, the code is pretty much unchanged from the original GroupManager _(and the build: true issue was present in both)._

However, this one I have to because there's no work-around or cause, other than something in EssentialsX being wrong. 

The problem is that only Opped individuals are able to use colorcodes on signs (and probably format codes as well but that wasn't tested). My admins who are in a group that has `essentials.signs.color` are unable to use them, nor are players who directly have the exact same permission assigned to them. I have tried also giving: `essentials.signs.*`, `essentials.sign.color`, `essentials.signs.colour`, `essentials.sign.colour`, all to no avail. 

So far, from what I can tell, it's only signs that are having the issue. Players and staff have no issues with using colorchat, colors in books, or in messages. This issue persists though restarts as well, since I have my server scheduled to auto-restart every morning at 4am. 

Thanks
-Form

**Comment by SupaHam** [comment]
Thanks for trying out EssentialsX. Sorry to hear your experiencing issues. A lot of the time it can easily be GroupManager, and I believe that is also the case now. A lot of signs code has remained unchanged - exception being game-breaking bug fixes.

My advice would be to ensure each individual player has `essentials.signs.color`, by using tools provided by the permissions plugin.

P.S. we've removed international `ou` spelling, i.e. `essentials.signs.colour` is not used.

**Comment by Formula350** [comment]
(Yea, I figured the international spelling wasn't going to work, but I had to try it if only to be thorough 😄)

What exactly has changed in EssX that has caused it to no longer be compatible with GroupManager in the very-random ways that it is? Of the essentials permissions we use, this is the only one so far that isn't functional. In my eyes *(which are almost completely ignorant to the world of coding)*, if it were GroupManager as the cause of the issue, then it'd exhibit this behavior across all of the EssX permissions, but since that isn't the case I can't help but wonder if it's not some oops in the EssX code? Was talking to another server owner last night who also plays on mine (and happened to have donated for the Colored Signs pack, when it worked in 1.8), and he mentioned having the same issue, eventually having to use another plugin in order to accomplish this goal. I'll have to ask him what permissions plugin he was using, but for some reason I want to say it was PeX.

But yes, the way I have it setup is a donation package which assigns that permission to their username. It runs: `/manuaddp <username> essentials.signs.color`
It's also added to certain groups as `- essentials.signs.color`

I dunno... *shrug* I'll take a look at the Plugin.yml and maybe if I set `essentials.signs.color` to be enabled by default, and revoke it with `- -essentials.signs.color` in the groups, that it being added to the user's specific permissions will allow it to function. :crossed_fingers: 

**EDIT:** As a followup, before modifying the Plugin.yml, I just now tried with a user by giving them permissions, then having her test inbetween each and these are the results...
Prior to adding, had user test - _Colored and Format do not work_
Gave `essentials.signs.color` - _Colored signs do not work_
Gave `essentials.signs.format` - _Colored and Format (used bold in the test) do not work_
Gave `essentials.signs.*` & `essentials.sign.* - _Colored, Format, and Magic do not work_

**UPDATE:** I edited the Plugin.yml and added these lines:
````yaml
  essentials.signs.color:
    default: true
    description: Testing to use Colors on signs.  -Formula350
  essentials.signs.format:
    default: true
    description: Testing to use Formatting on signs. -Formula350
  essentials.signs.magic:
    default: true
    description: Testing to use Obfuscation on signs. -Formula350
  essentials.signs.*:
    default: op
    description: Technically not needed, but adding just to see if it'll help. -Formula350 
    children:
      essentials.signs.color: true
      essentials.signs.format: true
      essentials.signs.magic: true
````
After uploading the modified plugin I restarted the server and had that player try again... Sadly, these did not seem to help (or maybe they didn't even register with EssX?).
