### ISSUE TITLE
essentials kits problem

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#1722]
Im having a problem with Essentials kits. I have made many kits that have many enchants. The problem is... essentials is adding its own enchants. example: - 278 1 efficiency:5 unbreaking:5 fortune:5 name:&9{USERNAME}&9's_God_Pickaxe lore:{DATE} . THis works fine but when i receive the kit it has sweeping edge... and so do all my kit items for that matter.
```yaml
god:
    delay: 2678400
    items:
      - 310 1 protection:5 unbreaking:5 protection_fire:5 name:&9{USERNAME}&9's_God_Helmet lore:{DATE}
      - 311 1 protection:5 unbreaking:5 protection_fire:5 name:&9{USERNAME}&9's_God_Chestplate lore:{DATE}
      - 312 1 protection:5 unbreaking:5 protection_fire:5 name:&9{USERNAME}&9's_God_Leggings lore:{DATE}
      - 313 1 protection:5 unbreaking:5 protection_fire:5 name:&9{USERNAME}&9's_God_Boots lore:{DATE}
      - 276 1 sharpness:5 unbreaking:5 fire_aspect:2 knockback:5 looting:5 name:&9{USERNAME}&9's_God_Sword lore:{DATE}
      - 278 1 efficiency:5 unbreaking:5 fortune:5 name:&9{USERNAME}&9's_God_Pickaxe lore:{DATE}
      - 277 1 efficiency:5 unbreaking:5 fortune:5 name:&9{USERNAME}&9's_God_Shovel lore:{DATE}
      - 279 1 sharpness:5 unbreaking:5 fire_aspect:2 name:&9{USERNAME}&9's_God_Axe lore:{DATE}
      - 56 32
      - 60 1
      - 322:1 16
```
![2017-12-22_11 00 25](https://user-images.githubusercontent.com/13128666/34305023-5862421e-e70a-11e7-9b85-5bae947f9d58.png)
