### ISSUE TITLE
Book systems don't work 

### ISSUE THREAD

**Issue by Medialo** [EssentialsX/Essentials#1725]
EssentialsX version (`/essentials`): Essentials 2.0.1-b556

Server software (`/version`): Spigot 5695bca-53fccdf MC:1.12.2  (API version 1.12..2-R0.1-SNAPSHOT)

Server (logs/latest.log):
[latest.log](https://github.com/EssentialsX/Essentials/files/1585768/latest.log)

EssentialsX config (if applicable): 

My problem is simply that Essentials doesn't create a book. yml file when ordering /kit color, so give me a book with the message: Invalid Tag Book.
So I have to go back to an old version for the books to work.

**Comment by drtshock** [comment]
Can you show your book.yml and kits from your config?

**Comment by Medialo** [comment]
Hello, here is the config file (kit), but the book. yml file is not created, when the server starts or even when ordering /kit color for example.  .
```
####
kits:
  tools:
    delay: 10
    items:
      - 272 1
      - 273 1
      - 274 1
      - 275 1
  dtools:
    delay: 600
    items:
      - 278 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
      - 277 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
      - 298 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
      - 279:780 1
  notch:
    delay: 6000
    items:
      - 397:3 1 player:Notch
  color:
    delay: 6000
    items:
      - 387 1 title:&4Book_&9o_&6Colors author:KHobbits lore:Ingame_color_codes book:Colors
  firework:
    delay: 6000
    items:
      - 401 1 name:Angry_Creeper color:red fade:green type:creeper power:1
      - 401 1 name:Starry_Night color:yellow,orange fade:blue type:star effect:trail,twinkle power:1
      - 401 2 name:Solar_Wind color:yellow,orange fade:red shape:large effect:twinkle color:yellow,orange fade:red shape:ball effect:trail color:red,purple fade:pink shape:star effect:trail power:1


  ```
