### ISSUE TITLE
Kit bug

### ISSUE THREAD

**Issue by RainOfPain125** [EssentialsX/Essentials#1736]
EssentialsX version (`/essentials`): Essentials reloaded 2.0.1-b557

Server software (`/version`): git-Paper-1288

Server (logs/latest.log): n/a

EssentialsX config (if applicable): 
```
kits:
  Food:
    delay: 86400
    items:
      - 364 16
      
  Clothes:
    delay: 86400
    items:
      - 298 1 lore:&bCap worn by brand new RA members name:&1RoyalArms Cap 
      - 299 1 lore:&bTop worn by brand new RA members name:&1RoyalArms Top color:0,0,255
      - 300 1 lore:&bBottoms worn by brand new RA members name:&1RoyalArms Bottoms color:255,255,0
      - 301 1 lore:&bBoots worn by brand new RA members name:&1RoyalArms Boots color:0,0,0
```

My kit setup used to work on earlier server runs, but now it doesn't. The item meta-data just gets jank -

https://s18.postimg.org/eods6wxkp/2017-12-29_22.55.34.png
