### ISSUE TITLE
World aliases for chat formatting

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#1793]
Have a `world-alias` section under `chat` in the config, which allows servers to set aliases for different worlds. These aliases can then be substituted into chat formats with a token like `{WORLDALIAS}`.

For example:
```
chat:
# ...
    format: "{WORLDALIAS} - {DISPLAYNAME}: {MESSAGE}"
    world-aliases:
        plots: "&lP&r"
        test: "&mT&r"
```

This would lead to messages being formatted as such:
> **P** - MD678685: hello
> ~~T~~ - LaxWasHere: ./supaham

If no alias is specified, it could default to the world name.
