### ISSUE TITLE
"&r" character not working in kit colors

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#192]
Like the title says. 
Here's a picture of the bug: https://gyazo.com/410eb03707910c89803853196f7218bd

book.txt

```
#Colors
Minecraft colors:
&0 &&0  &1 &&1  &2 &&2  &3 &&3
&4 &&4  &5 &&5  &6 &&6  &7 &&7
&8 &&8  &9 &&9  &a &&a  &b &&b
&c &&c  &d &&d  &e &&e  &f &&f
&0 
&&k &kMagic&r   &&l &lBold
&&m &mStrike&r  &&n &nUline
&&o &oItalic&r   &&r &rReset
```

config.yml

```
kits:
  color:
    delay: 6000
    items:
      - 387 1 book:Colors title:&4Book_&9o_&6Colors author:KHobbits lore:Ingame_color_codes
```
