### ISSUE TITLE
Essentials createkit & potions

### ISSUE THREAD

**Issue by Flavourized** [EssentialsX/Essentials#1965]
### Information

Full output of `/ess version`: Essentials 2.0.1-b612

EssentialsX config:

```
  potions:
    delay: -1
    items:
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:heal power:1 duration:1
    - SPLASH_POTION 1 effect:speed power:2 duration:60
    - SPLASH_POTION 1 effect:speed power:2 duration:60
    - SPLASH_POTION 1 effect:strength power:2 duration:60
    - SPLASH_POTION 1 effect:strength power:2 duration:60
    - SPLASH_POTION 1 effect:fireresist power:1 duration:400
``` 

### Details

Describe your issue here.

Issue 1: When using `/createkit` to create a kit with splash potions or  other potioons, it will not save the effect of the potions itself. After saving the kit, and then running `/kit potions` (this is what i named the kit`, i get splash potions with no effects. 

Issue 2: When countering the issue above (and manually inputting the potions into `kits.yml`, you can see in my config i put SPLASH_POTION and did the potions as the essentials wiki describes ItemMeta. After doing this and reloading essentials, then typing `/kit potions`, i received the correct effects, but only got normal potions (ones that you drink instead of throw). There are no errors, no messages in config.
