### ISSUE TITLE
Creeper damage issue

### ISSUE THREAD

**Issue by LogGits** [EssentialsX/Essentials#1982]
### Information

Full output of `/ess version`:

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1402 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.1.25
Vault version: 1.6.10
EssentialsXProtect version: 2.15.0.1

### Details

Has there been anything implemented to alter the damage of creepers. I have recently noticed that creepers do at max half a heart of damage to a player with diamond armour. Is there a setting i am missing that alters this? I disabled essentials and the damages was back to normal. Any ideas?

Incase its important (essentialsprotect section of config.yml):
```yaml
protect:

  # General physics/behavior modifications.
  prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false
    fire-spread: true
    lava-fire-spread: true
    flint-fire: false
    lightning-fire-spread: true
    portal-creation: false
    tnt-explosion: true
    tnt-playerdamage: false
    tnt-minecart-explosion: true
    tnt-minecart-playerdamage: false
    fireball-explosion: true
    fireball-fire: false
    fireball-playerdamage: false
    witherskull-explosion: true
    witherskull-playerdamage: false
    wither-spawnexplosion: true
    wither-blockreplace: true
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-blockdamage: true
    enderdragon-blockdamage: true
    enderman-pickup: true
    villager-death: false
    # Monsters won't follow players.
    # permission essentials.protect.entitytarget.bypass disables this.
    entitytarget: false
    # Prevent the spawning of creatures.
    spawn:
      creeper: false
      skeleton: false
      spider: false
      giant: false
      zombie: false
      slime: false
      ghast: false
      pig_zombie: false
      enderman: false
      cave_spider: false
      silverfish: false
      blaze: false
      magma_cube: false
      ender_dragon: false
      pig: false
      sheep: false
      cow: false
      chicken: false
      squid: false
      wolf: false
      mushroom_cow: false
      snowman: false
      ocelot: false
      iron_golem: false
      villager: false
      wither: false
      bat: false
      witch: false
      horse: false

  # Maximum height the creeper should explode. -1 allows them to explode everywhere.
  # Set prevent.creeper-explosion to true, if you want to disable creeper explosions.
  creeper:
    max-height: -1

  # Disable various default physics and behaviors.
  disable:
    # Should fall damage be disabled?
    fall: false

    # Users with the essentials.protect.pvp permission will still be able to attack each other if this is set to true.
    # They will be unable to attack users without that same permission node.
    pvp: false

    # Should drowning damage be disabled?
    # (Split into two behaviors; generally, you want both set to the same value.)
    drown: false
    suffocate: false

    # Should damage via lava be disabled?  Items that fall into lava will still burn to a crisp. ;)
    lavadmg: false

    # Should arrow damage be disabled?
    projectiles: false

    # This will disable damage from touching cacti.
    contactdmg: false

    # Burn, baby, burn!  Should fire damage be disabled?
    firedmg: false

    # Should the damage after hit by a lightning be disabled?
    lightning: false

    # Should Wither damage be disabled?
    wither: false

    # Disable weather options?
    weather:
      storm: true
      thunder: true
      lightning: true
```
