### ISSUE TITLE
Help topics

### ISSUE THREAD

**Issue by jpeaceau** [EssentialsX/Essentials#2028]
It'd be awesome if there were help topics to be configured /help <index> where the configuration would look like this

```
help-topics:
   default: (would be used if there are no args)
        index: <description>
   index:
        command: <description>
        another-cmd: <desc>
   another-index:
        command: <description>
        another-cmd: <desc>
```
