### ISSUE TITLE
Theme color

### ISSUE THREAD

**Issue by BenjaminHoegh** [EssentialsX/Essentials#2098]
Add support for changing the theme color of the plugin

as it is right now you need to edit messages.properties to get your own theme color, this issn't very handsome when new updates came out, will be nice to have this in the settings insted

**Comment by pop4959** [comment]
This may be interesting to look into once 1.16 drops. With more colors available, it's likely that major changes will be made to Bukkit w.r.t. setting colors. We might want to switch over to having a color map instead of hard coding colors into everything.

**Comment by mdcfe** [comment]
Adding such a setting would require either a hacky replace on all messages or an overhaul to the current formatting system, as well as special consideration for people who want to keep editing their messages files as they are right now. It's not that difficult for users to do a find-and-replace on EssentialsX's current messages files, and I'm not a fan of doing hacky workarounds inside EssentialsX to support this, so it'll have to wait until larger changes are made to messaging inside EssX.

**Comment by rErEaT** [comment]
@md678685 what is the color codes in the message file? :)

**Comment by quick007** [comment]
> This may be interesting to look into once 1.16 drops. With more colors available, it's likely that major changes will be made to Bukkit w.r.t. setting colors. We might want to switch over to having a color map instead of hard coding colors into everything.

aight 1.16 dropped

**Comment by Evidentsinger14** [comment]
as of the Adventure update, this is now possible. locate the following lines in your config.yml. if you have an old version of the config, you may need to regenerate, or add the following lines in manually. 

```yaml
# Change the default primary and secondary colours used in EssentialsX messages.
# Some messages may use custom colours, which will need to be edited in the appropriate message files.
# For more information on customising messages, see https://essentialsx.net/wiki/Locale.html
message-colors:
  primary: '#ffaa00'
  secondary: '#ff5555'
```
