### ISSUE TITLE
EssentialsX Spawn

### ISSUE THREAD

**Issue by DesperoKF** [EssentialsX/Essentials#2373]
I have Spigot 1.12.2 (its a Bungeecord server) 
EssentialsX-2.16.0.26
EssentialsXChat-2.16.0.26
EssentialsSpawn-2.16.0.26

I am on my Lobby Server and i execute /setspawn. Result: Spawn set to default
My problem is that I do not spawn at join. there where I last logged out

spawn.yml
```yaml
spawns:
  default:
    world: Lobby
    x: 267.56979057453503
    y: 65.0
    z: -1.6398878628761109
    yaw: 358.49973
    pitch: 13.950009
  newbie:
    world: Lobby
    x: 267.57579768468725
    y: 65.0
    z: -1.6344856999040354
    yaw: 358.49973
    pitch: 13.950009
```

### My Spawn Config (EssentialsX config.yml)
```yaml
############################################################
# +------------------------------------------------------+ #
# |            Essentials Spawn / New Players            | #
# +------------------------------------------------------+ #
############################################################

# This section requires essentialsspawn.jar to work.

newbies:
  # Should we announce to the server when someone logs in for the first time?
  # If so, use this format, replacing {DISPLAYNAME} with the player name.
  # If not, set to ''
  announce-format: ''
  #announce-format: '&dWelcome {DISPLAYNAME}&d to the server!'

  # When we spawn for the first time, which spawnpoint do we use?
  # Set to "none" if you want to use the spawn point of the world.
  spawnpoint: newbie

  # Do we want to give users anything on first join? Set to '' to disable
  # This kit will be given regardless of cost and permissions, and will not trigger the kit delay.
  kit: ''
 # kit: tools

# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: highest

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: highest

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

# Teleport all joining players to the spawnpoint
spawn-on-join: true
# The following value of `guests` states that all players in group `guests` will be teleported to spawn when joining.
#spawn-on-join: default
# The following list value states that all players in group `guests` and `admin` are to be teleported to spawn when joining. 
#spawn-on-join:
#- owner
#- guests
#- admin

# End of file <-- No seriously, you're done with configuration.
```
