### ISSUE TITLE
[1.15.1] My kit is not working (items with HideFlags, coloured leather cap, enchantments, and custom names and lores)

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2965]
### Information

Full output of `/ess version`:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-62 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
```

**Server log:** https://gist.github.com/DeleteMetaInf/ce1566af719c7b631abfd074c59490d8

**EssentialsX config** https://gist.github.com/DeleteMetaInf/4d513deac4d3b93e009cdfa7311d8c09

### Help request

**Problem**
My kit is not working.

When I use the /kit command to give myself the kit, I only get the axe and 5 bread. I don’t get the rest of the items. The error I get is ”Error: That kit is improperly defined. Contact an administrator.”

Kit code from kits.yml:
```
  tin:
    delay: -1
    items:
    - stone_axe 1 name:&7The_Tin_Axe lore:&bSmite_I_ damage_undead:1 itemflags:HIDE_ENCHANTS
    - bread 5
    - leather_helmet 1 name:&7The_Tin_Cap lore:&bProjectile_Protection_I_ protection_projectile:1
      itemflags:HIDE_ENCHANTScolor:10329495
    - wheat_seeds 1
    - cobblestone 64
```

The kit was created in-game using the /kitcreate command.

**What I have tried**
I’ve tested whether it’s due to the HideFlags:1 NBT tag, the custom name and lore text, or the coloured leather armour, but any of those on their own works just fine in a kit. This kit in particular, though, does not.

**Screenshots**
![Kit issue](https://user-images.githubusercontent.com/59761487/72913936-2ec2b380-3d3e-11ea-828b-66d36004db47.png)
