### ISSUE TITLE
Per group chat format

### ISSUE THREAD

**Issue by zuhir** [EssentialsX/Essentials#3179]
Due i was been ignored in Discord server and i can't get any solution, i report this again now as bug or not worked as intended

Information
Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
EssentialsX version: 2.17.2.59
LuckPerms version: 5.0.130
PlaceholderAPI version: 2.10.5
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.2.59
EssentialsXSpawn version: 2.17.2.59

EssentialsX don't detect my group and uses default chat format

I have this in config:

```
  format: '{DISPLAYNAME}&7: {MESSAGE}'

  group-formats:
    default: '{DISPLAYNAME}&7: {MESSAGE}'
    mod: '{DISPLAYNAME}&f: {MESSAGE}'
    admin: '{DISPLAYNAME}&f: {MESSAGE}'
```
I'm at admin group but on chat i write like default, i checked my groups and only has admin group
LuckPerms's groups names are lowercase in every case
