### ISSUE TITLE
Using {PLAYER} in kits lore.

### ISSUE THREAD

**Issue by BlitzOffline** [EssentialsX/Essentials#3448]
#3106 # Information

**Full output of `/ess version`**:

```
>.... [13:22:37 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-353 (MC: 1.15.2)
>.... [13:22:37 INFO]: EssentialsX version: 2.17.2.146
>.... [13:22:37 INFO]: PlaceholderAPI version: 2.10.6-DEV-${BUILD_NUMBER}
>.... [13:22:37 INFO]: LuckPerms version: 5.1.26
>.... [13:22:37 INFO]: Vault version: 1.7.2-b107
>.... [13:22:37 INFO]: Citizens version: 2.0.26-SNAPSHOT (build 1970)
>.... [13:22:37 INFO]: EssentialsXGeoIP version: 2.17.2.146
>.... [13:22:37 INFO]: EssentialsXSpawn version: 2.17.2.146
```

**Server log**: https://gist.github.com/BlitzGamer-88/689b4b332eabdb2667efb01a194c9161

**EssentialsX config**: https://gist.github.com/BlitzGamer-88/84d88969d9ac889ddb7112a1712c1738

### Details

**Description**  
If a player has underscores in his username and I add `{PLAYER}` to the lore of an item in kits.yml his name will have spaces instead. Tried using '\{PLAYER}' just in case that maybe \ is canceling the spaces but doesn't work.

**Steps to reproduce**  
Go in `plugins/Essentials/kits.yml` and add this example kit:
```
  example:
    delay: -1
    items:
    - diamond_sword 1 knockback:2 loot_bonus_mobs:3 damage_all:3 durability:3 name:&aKit_Example lore:|&7Owner:_{PLAYER}
```

**Expected behavior**  
I would like for it to only replace underscores in text not in Placeholders or at least there to be a special character or something to cancel the changing of underscores to spaces.

**Screenshots**  
https://i.imgur.com/rDsvgxl.png
