### ISSUE TITLE
Functions are using Essentials commands

### ISSUE THREAD

**Issue by UltraBlackLinux** [EssentialsX/Essentials#3502]
### Information

Full output of `/ess version`: 2.17.2.0

**Server log:** https://gist.github.com/UltraBlackLinux/163ec4ca0e587dcc8b89aee7eaad2764

**EssentialsX config** https://gist.github.com/UltraBlackLinux/74ec76a6dcffd8d12192bb31bccc0a07

### Help request

**Problem**
Functions seem to use EssentialsX commands Instead of vanilla ones, causing tp and more not to work

**What I have tried**
commands.yml: 
```

command-block-overrides:
  - "tp"
unrestricted-advancements: false
aliases:
  icanhasbukkit:
  - version $1-
  kill:
  - minecraft:kill $1-
  tp:
  - minecraft:tp $1-
  gamemode:
  - minecraft:gamemode $1-
  summon:
  - minecraft:summon $1-
  reload:
  - minecraft:reload $1-
```

**Additional Info**
Related to #1458
Im on Magma (Spigot + Forge)
