### ISSUE TITLE
/tpr not respecting min-range

### ISSUE THREAD

**Issue by Bobcat00** [EssentialsX/Essentials#3870]
### Information

**Full output of `/ess version`:**

```
Server version: 1.16.4-R0.1-SNAPSHOT git-Spigot-628435a-6917945 (MC: 1.16.4)
EssentialsX version: 2.18.2.0
LuckPerms version: 5.2.35
Vault version: 1.7.3-b131
EssentialsXChat version: 2.18.2.0
EssentialsXGeoIP version: 2.18.2.0
EssentialsXSpawn version: 2.18.2.0
```

**EssentialsX config:**

https://gist.github.com/Bobcat00/587ba22e6bd272c02436511ba56c1ea1

### Details

**Description:**  

When doing /tpr the teleport destination does not respect the min-range parameter. For example with a min-range of 2000 and a center point of 285.5 65.0 510.5, I was teleported to the following locations:
**-765** 69 -2627
**294** 69 -2445
**66** 71 -4212
5036 64 **-906**
4501 78 **465**
The first three have improper X coordinates, the last two have improper Z coordinates (see expected behavior below).

(To be clear, there were other destinations in the proper range.)

tpr.yml:
```
# Configuration for the random teleport command.
# Some settings may be defaulted, and can be changed via the /settpr command in-game.
pre-cache: false
min-range: 2000.0
excluded-biomes:
- cold_ocean
- deep_cold_ocean
- deep_frozen_ocean
- deep_lukewarm_ocean
- deep_ocean
- deep_warm_ocean
- frozen_ocean
- frozen_river
- lukewarm_ocean
- ocean
- river
- warm_ocean
max-range: 5000.0
center:
  world: LanaPug
  x: 285.5
  y: 65.0
  z: 510.5
  yaw: -359.69977
  pitch: -4.1879714E-5
```

**Steps to reproduce:**  

Configure tpr.yml as shown (you'll have to specify a different world), use F3 to display the coordinates, then do /tpr multiple times. Observe the location to which you are teleported.

**Expected behavior:**  

For the location to which you are teleported:
X should always be less than -1715 OR greater than 2285
Z should always be less than -1490 OR greater than 2510
