### ISSUE TITLE
Issue with grouping on /list

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#457]
It seems like grouping /list items is only possible with the first entry.

```
list:
    # To merge groups, list the groups you wish to merge
    #Staff: owner admin moderator
    Staff: Tech Admin smod mod
    Helfer: Helfer
    Legacy: Senior
    Spieler: Spieler Voteaktion Votearmour Votemmo
```

The `Staff` grouping works well. 
But players in the groups `Voteaktion`, `Votearmour` or `Votemmo` getting listed separately. No clue why they're not grouped with `Spieler`.

2.0.1-b206 @ Spigot 1.8.8
I know, a bit outdated. Planning to update soon. Anyway I took a look at the earlier issue reports and could not find anything similar, so there might have been no change in this code since then.

Updated to 296, but no change.
