### ISSUE TITLE
Shields in Kits

### ISSUE THREAD

**Issue by drtshock** [EssentialsX/Essentials#474]
Shield patterns and colors do not work in kits. They have similar properties as BannerMeta and will likely inherit those. We will have the same syntax for each. Once https://hub.spigotmc.org/jira/browse/SPIGOT-1828 is resolved, we will be able to have shields in kits with only a 3 line change.

**Comment by HunterJacobs** [comment]
What about being able to have armor spawn in the armor slots and shield slot when /kit (name) is executed?

**Comment by drtshock** [comment]
completely separate issue.

**Comment by Nezz202** [comment]
I still get this issue even in the very latest release of EssentialsX nearly two years later. Is there indication if there is a fix for this anywhere?

I am using Paper 1.13.2, EssentialsX 2.16.0.32

When holding a banner with the shield I want to make into a kit, I run /kitcreate and it puts this in the kits.yml

```
test1:
    delay: 1
    items:
    - SHIELD 1 tts,16351261 bts,11546150 gru,16351261 bo,10329495 mr,16701501 flo,16701501
```
