### ISSUE TITLE
command-cost doesn't work in any situation where a subcommand/argument is used

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4856]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

[removed]

### Error log (if applicable)

N/A

### Bug description

I've placed a few commands into the command-costs section of the config and in my kits file. However, if any subcommand/argument is used `(/kit <kit>`, `/sethome <home>`, `/home <home>` etc.) it doesn't take away any money, I've been looking through so many other reports and posts (I mean a lot) and some are marked as closed or resolved but no actual solution was given.

### Steps to reproduce

Add a cost to a command that requires or has an argument space (kit, home, etc.)
e.g. 
```
command-costs:
    kit-tools: 100
    sethome: 100
    home: 100
    # Back will work as there's no arguments
    back: 100
```

Run the command

Observe issue

### Expected behaviour

Money will be removed when the command is run

### Actual behaviour

Money is not removed when the command is run

### Edits

Me being dumb and not knowing how formatting works
