### ISSUE TITLE
Log Discord -> Minecraft messages in console too

### ISSUE THREAD

**Issue by BaxAndrei** [EssentialsX/Essentials#5252]
### Feature description

I think it would be good to log in the server console the messages that someone sends on the discord channel, regardless of whether they are players who have access to see the message or not

### How the feature is useful

You can keep records directly from the console logs respectively from the console respectively from the docker container. It is especially useful when you don't have access to discord or the server.

**Comment by JRoy** [comment]
There is already an option for this in the config;
```yml

**Comment by JRoy** [comment]
There is already an option for this in the config
```yml
# Chat relay settings
# General settings for chat relays between Minecraft and Discord.
# To configure the channel Minecraft chat is sent to, see the "message-types" section of the config.
chat:
  ...
  # A list of Discord channels which should be logged to console.
  # If you want to use the channels below, remember to uncomment the line by removing the '#' before the '-'.
  relay-to-console:
    #- primary
    #- chat
```
