### ISSUE TITLE
Add chat format configuration for each chat type for a group

### ISSUE THREAD

**Issue by Flowsqy** [EssentialsX/Essentials#5332]
### Feature description

Currently, we can configure chat format for a specific group. We can also specify the format of a specific chat type in the messages file. But we can not change the tags depending of the chat type.
Let's say we want two different formats for the groups 'admin' and 'player' and the chat type 'shout' and 'local'. We could configure something like that:
```yaml
group-formats:
  admin:
    local: '{WORLDNAME} &4{DISPLAYNAME}&7:&r {MESSAGE}'
    shout: '{WORLDNAME} &c[{GROUP}]&r &4{DISPLAYNAME}&7:&c {MESSAGE}'
  player:
    local: '{WORLDNAME} &4r{DISPLAYNAME}&7:&r {MESSAGE}'
    shout: '{WORLDNAME} &a[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'
```

### How the feature is useful

It gives servers owners a better control over the chat format. It's can especially useful in some cases where chat messages become very long as there are sometimes a lot of information to display (group, world, player name, (team, jobs, etc...) )  and could enhance readability. (For example, a lot of tag are useless when you ask a question with '?')
