### ISSUE TITLE
Clarify commands defined in kits

### ISSUE THREAD

**Issue by YanisBft** [EssentialsX/Essentials#5354]
### Feature description

Even though kits can contain commands executed when you receive a kit, it's not really clear to have them defined in `items` list.
I suggest to move commands to a `commands` list, as shown in the simple example below.

Before:
```
kits:
  dtools:
    delay: 600
    items:
      - dpickaxe 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
      - dshovel 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
      - lhelm 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
      - daxe:780 1
      - /broadcast {USERNAME} just got some fancy tools!
```

After:
```
kits:
  dtools:
    delay: 600
    items:
      - dpickaxe 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
      - dshovel 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
      - lhelm 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
      - daxe:780 1
    commands:
      - broadcast {USERNAME} just got some fancy tools!
```

### How the feature is useful

Helps to clarify that you can actually define commands, and avoid to rely on a single slash.
