### ISSUE TITLE
Other players can move players out of AFK mode by breaking block underneath

### ISSUE THREAD

**Issue by 42willow** [EssentialsX/Essentials#5412]
### Type of bug

Exploit

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2e9ea87da4b4402fa5ddfe93766d4990

### Bug description

Player A runs `/afk`
They are put in AFK mode

Player B breaks the block under Player A
Player A is put out of AFK mode

### Steps to reproduce

1. Use default config
2. Do `/afk`
3. Set the block underneath you to air with commands

### Expected behaviour

The player should stay in AFK mode, or the block underneath shouldn't be able to be broken (a new configurable setting?)

### Actual behaviour

The player exits AFK mode

----

Currently, with this config, it can be kind of fixed..

```yaml
cancel-afk-on-move: false
cancel-afk-on-chat: false
cancel-afk-on-interact: false # Need this set to false! Shouldn't!
freeze-afk-players: true
```
