### ISSUE TITLE
Cumulative homes

### ISSUE THREAD

**Issue by IdaEdz** [EssentialsX/Essentials#6013]
### Feature description

I'd like have a admin command to add more home to a player. i.e. /addhomes (player) <#>
The server would then do addition to that players current number of home and add the number specified.
The user would then have a individual number of homes based on their play-style/ranks/purchases.

There could also be a decreasing command if the player has been revoked a number of homes due to loss of a rank or similar.
i.e. /removehomes (player) <#>

I didn't look into how number of home are stored currently. For this to work one would need some form of database. I cannot see this working with permissions.

### How the feature is useful

**Usecase long time player need more homes**
As you progress on a server the need for more homes increase over time. You build more things further away, you get more farms and you want to visit more people. Instead of deleting a home and balance if you need it or not. The options to acquire more home in some way provided by the server. Through play or pay. In other words you have to work for it.

**Usecase Ranking**
With this feature the administrator would be able to setup multiple lines of rank systems and purchase options for players to accumulate homes individually. When you gain a rank the server runs /addhomes to that player or when he loses a rank it runs /removedhomes 

Say for example that the server has paid ranks available with 10, 12 and 14 homes respective. And you also have Play-based rank-system, where you rank up after X amount of playtime, levels (like mcmmo and jobs) and voting, adding 1-4 homes/rank. Max 8 home at the top rank.

In the current state a player would have no reason to rankup to get more homes. Instead he would spring for more money and buy the highest rank directly. But with the addition of adding homes to your individual total the player could still gain something from playing more and spring for expansive extra homes later when needed.

**Usecase shopping**
With a adminshop one could make it possible to buy more homes dynamically. i.e. click a sign, server runs /addhomes, deduct money and the player receive X amount more home(s) to use. 

**Comments**

Obviously this could have more synergies and usecases with a lot of different plugins and types of servers. I'm just playing on one server and can't thing of everything.

**Comment by JRoy** [comment]
You can use permissions with the `sethomes-multiple` feature in the config to accomplish this.


```yml
# Allow players to have multiple homes.
# Players need essentials.sethome.multiple before they can have more than 1 home.
# You can set the default number of multiple homes using the 'default' rank below.
# To remove the home limit entirely, give people 'essentials.sethome.multiple.unlimited'.
# To grant different home amounts to different people, you need to define a 'home-rank' below.
# Create the 'home-rank' below, and give the matching permission: essentials.sethome.multiple.<home-rank>
# For more information, visit http://wiki.ess3.net/wiki/Multihome
sethome-multiple:
  default: 3
  vip: 5
  staff: 10
```

**Comment by IdaEdz** [comment]
Are the permissions stackable?

If I have a rank called "buy1morehome"
And give a player that rank 5 times.

Will that player have X homes + buy1morehome * 5?


- Player start with 2 home.
- Player get rank X with 5 homes.
- Player now have 2+5=7 homes.
- Player acquired buy1morehome-rank 5  times. (Think clicking a sign)
- Player now have 7+1*5=12 homes.

Permission would be:
- Essentials.sethome.multiple.default
- Essentials.sethome.multiple.rankx
- Essentials.sethome.multiple.buy1morehome
- Essentials.sethome.multiple.buy1morehome
- Essentials.sethome.multiple.buy1morehome
- Essentials.sethome.multiple.buy1morehome
- Essentials.sethome.multiple.buy1morehome

**Comment by JRoy** [comment]
You cannot give someone a permission twice. You can however make a new permission for 2 homes, 3 homes, etc.

**Comment by IdaEdz** [comment]
I wanted to give 1 home multiple times over to infinity. Limitless, but to a cost per home.

```
I could make a very large list of psudo-ranks
sethome-multiple:  
  default: 3
  # essentials.sethome.multiple.buy1home-1
  buy1home-1: 1
  # essentials.sethome.multiple.buy1home-2
  buy1home-2: 1
  # essentials.sethome.multiple.buy1home-3
  buy1home-3: 1
  ...
  # essentials.sethome.multiple.buy1home-n
  buy1home-n: 1
```


And give permissions like this:
```
- Essentials.sethome.multiple.buy1home-1
- Essentials.sethome.multiple.buy1home-2
- Essentials.sethome.multiple.buy1home-3
- ...
- Essentials.sethome.multiple.buy1home-n
```
 
This would give the player 1(n) homes.
