### ISSUE TITLE
Incompatibility with DeluxeTags after Essentials dev version switched to Paper chat events

### ISSUE THREAD

**Issue by BlueGuineaPig78** [EssentialsX/Essentials#6048]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=yLKkiiK9cW

### Bug description

I posted this to discord and it was suggested that I open an issue for it. We use the DeluxeTags plugin (not updated since 2022 but, it still works and we like it). We use 
`default: '&f{DISPLAYNAME}&r{deluxetags_tag}:&f {MESSAGE}'`
in the EssentialsChat config group section. This still works in Essentials dev version 166, but broke in 168 (I skipped 167, then went back to 166 when I discovered the chat formatting problem). I assume this has to do with the update in Esssentials dev version to use Paper's chat events.

### Steps to reproduce

Log in and type something in chat.

### Expected behaviour

Placeholder should be replaced by the player's selected tag.

### Actual behaviour

Placeholder doesn't get replaced by the player's selected tag.

**Comment by JRoy** [comment]
That's not a placeholder supported by Essentials. DeluxeTags needs to be updated to support Paper's Chat Events.

**Comment by JRoy** [comment]
This is an issue with whatever plugin is injecting that into the chat message, they must add support for Paper's `AsyncChatEvent`.

In the meantime, you may download the latest dev build and in that chat section of your `config.yml`: add `paper-chat-events` and set it to `false`, then restart your server

```yaml
chat:
  # Whether EssentialsX should use Paper's modern chat event system in 1.16.5+.
  # This is required for modern chat features such as hover events and click events.
  # If you're experiencing issues with other plugins that use the chat event system, you can disable this.
  # You must restart your server after changing this setting.
  paper-chat-events: false
```
