### ISSUE TITLE
Error in build 168

### ISSUE THREAD

**Issue by novrom1982** [EssentialsX/Essentials#6051]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=UxHWsQPlxS

### Bug description

After the update, an error appeared in the console when displaying a message in the [Chat Game](https://www.spigotmc.org/resources/chat-games-mini-game-rewards-configurable.13703/).

### Steps to reproduce

When players in the game chat give the correct answer, an error appears in the console

### Expected behaviour

There should only be a player response

### Actual behaviour

Player's response and error

Could not pass event AsyncChatEvent to EssentialsChat v2.21.0-dev+169-69ed07a
java.lang.NullPointerException: null

**Comment by Bobcat00** [comment]
My fork of Pwnfilter does this ,too.

**Comment by JRoy** [comment]
In the meantime while I investigate this issue, you may download the latest dev build and in that chat section of your `config.yml`: add `paper-chat-events` and set it to `false`, then restart your server

```yaml
chat:
  # Whether EssentialsX should use Paper's modern chat event system in 1.16.5+.
  # This is required for modern chat features such as hover events and click events.
  # If you're experiencing issues with other plugins that use the chat event system, you can disable this.
  # You must restart your server after changing this setting.
  paper-chat-events: false
```
