### ISSUE TITLE
Problem with variable chat {jobs}

### ISSUE THREAD

**Issue by DjeyMute** [EssentialsX/Essentials#6056]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=v4idpbHNjN

### Bug description

When I use the {jobs} in the EssentialsChat it's not displaying the jobs of the player.

### Steps to reproduce

     gdm_survie16_fondateur:
       shout: '&7[&2Octopia&7]&r{STELYTEAM_PREFIX}{DISPLAYNAME} &f➢ &9{MESSAGE}'
       local: '{jobs}{STELYTEAM_PREFIX}{DISPLAYNAME} &f➢ &9{MESSAGE}'

### Expected behaviour

See in the chat the jobs of the player

### Actual behaviour

In the chat we see that "{jobs}"

**Comment by JRoy** [comment]
This is an issue with whatever plugin is injecting that into the chat message, they must add support for Paper's `AsyncChatEvent`.

In the meantime, you may download the latest dev build and in that chat section of your `config.yml`: add `paper-chat-events` and set it to `false`, then restart your server

```yaml
chat:
  ...
  # Whether EssentialsX should use Paper's modern chat event system in 1.16.5+.
  # This is required for modern chat features such as hover events and click events.
  # If you're experiencing issues with other plugins that use the chat event system, you can disable this.
  # You must restart your server after changing this setting.
  paper-chat-events: false
```
