### ISSUE TITLE
Could not pass event AsyncChatEvent to EssentialsChat v2.21.0-dev+171-8313d52

### ISSUE THREAD

**Issue by jph4991** [EssentialsX/Essentials#6059]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=9R4uRwZNkp

### Error log (if applicable)

https://gist.github.com/jph4991/ac8081e8591ac6e1c9364bb394fd7937

### Bug description

Throwing random error code for AsyncChatEvent to EssentialsChat

### Steps to reproduce

Unknown

### Expected behaviour

Should not produce error code

### Actual behaviour

Produces error code

**Comment by JRoy** [comment]
In the meantime while I investigate this issue, you may download the latest dev build and in that chat section of your `config.yml`: add `paper-chat-events` and set it to `false`, then restart your server

```yaml
chat:
  # Whether EssentialsX should use Paper's modern chat event system in 1.16.5+.
  # This is required for modern chat features such as hover events and click events.
  # If you're experiencing issues with other plugins that use the chat event system, you can disable this.
  # You must restart your server after changing this setting.
  paper-chat-events: false
```
