### ISSUE TITLE
Kits new features

### ISSUE THREAD

**Issue by NewBestX** [EssentialsX/Essentials#612]
I have a feature request, can you add the option to set someone's armor directly when he gets a kit? So he doesn't have to open his inventory and put it on manually.
Another feature would be leaving blank slots in the kit, so I can for instance give the player 1 bow in the hotbar and arrows in another inventory slot (like slot 10).

Both these features can be implemented if an inventory slot number argument is added to the kit config, something like

```
pickaxe:
    delay: 1800
    items:
      - 2 257 1 efficiency:1
      - 9 320 16
      - 37 310 1 protection:3
```

This way, the person typing /kit pickaxe would get an iron pickaxe in the second slot, 16 cooked porkchops in slot 9, and a diamond helmet on his head (if the head is slot 37, I don't know the exact order). We will also have a slot 41 which is the left hand.

Another idea would be to add a slot 0 or slot -1, and the items given this slot would work just like the kits right now, will place the item in the first available slot (in case you don't want to override player's items).

Thank you!
