### ISSUE TITLE
Request: New Players custom motd chapter.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#69]
We have the option to announce a new player to the server, but no option to give this new player their own custom message when they join, This could be in the format of a config the same as announce-format, or a setting in the MOTD, A specific chapter name could be the display format #newbie for example.

**Comment by mdcfe** [comment]
This can be achieved by creating a custom text for newbies, creating a starter kit that just runs that specific custom text command and setting it as a starter kit for newbies, which wouldn't be achieving any more or less than adding direct support for this in EssentialsX Spawn.

**Comment by TomLewis** [comment]
A kit can run commands?! Whats the syntax, At a guess is it this?
```
kits:
# ------------------------------ #
#          STARTER KIT           #
# ------------------------------ #
  spawnkit:
    delay: 6000
    items:
      - customtext newbie
```
