### ISSUE TITLE
[BUG REPORT] Disable fly in The End

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#690]
Hey,

I disabled fly for players within The End, however theres a bug.

When they get hit by a Shulker, and they relog, they can just use fly even while it's disabled.

```
worlds:
  world2_the_end:
    permissions:
    - -essentials.fly
```

Are you able to fix this issue?
