### ISSUE TITLE
Cooldown issue.

### ISSUE THREAD

**Issue by Done84** [EssentialsX/Essentials#719]
Hi.
Cool downs only seem to work when commands don't have a argument.
For example:

``` yml
command-cooldowns:
  feed: 100 # 100 second cooldown on /feed command
  repair all: 100
  repair*: 100
  repair *: 100
  repair: 100
```

Feed works fine however /repair doesn't seem to work with any of those i tried.
