### ISSUE TITLE
How to add commands to kits

### ISSUE THREAD

**Issue by aboudbinabd** [EssentialsX/Essentials#894]
Hello can someone please teach me how to add commands to kits in essentials X.
Here's the kit:
```yaml
kits:
  Starter:
    delay: -1
    items:
    - 311:0 1 Protection:1 Name:&3Starter_&7Chestplate Lore:&7Welcome_to_&3Factions&7!
    - 312:0 1 Protection:1 Name:&3Starter_&7Leggings Lore:&7Welcome_to_&3Factions&7!
    - DIAMOND_HELMET:0 1 Protection:1 Name:&3Starter_&7Helmet Lore:&7Welcome_to_&3Factions&7!
    - 313:0 1 Protection:1 Name:&3Starter_&7Boots Lore:&7Welcome_to_&3Factions&7!
    - 364:0 32
    - golden_apple:0 16 
    - IRON_SWORD:0 1 sharpness:2 Name:&3Member_&7Sword Lore:&7Welcome_to_&3Factions&7!
    - 257:0 1 Efficiency:1 Name:&3Starter_&7Pickaxe Lore:&7Welcome_to_&3Factions&7!
    - 256:0 1 Efficiency:1 Name:&3Starter_&7Shovel Lore:&7Welcome_to_&3Factions&7!
    - 258:0 1 Efficiency:1 Name:&3Starter_&7Axe Lore:&7Welcome_to_&3Factions&7!
    - 17:0 64
    - 368:0 32
    - 333:0 1
    - obsidian:0 128 Lore:&6Use_this_to_build_your_base!
    - 54:0 4 Lore:&6Store_your_stuff!
    - /xp give {player} L30
    - /mp 2 give {player} 1
    - 395:0 1 Name:&3Note Lore:  &3Recommended_Version:,&7Minecraft_&61.8.8, ,&8HACKING_IS_&cNOT,&8ALLOWED
    - 50:0 64
    - 264:0 16
    - 373:16421
```
